-- reparar_columnas.sql
-- Agrega las columnas que puedan faltar en tablas creadas en intentos
-- anteriores, sin borrar nada de lo que ya tenías cargado.

ALTER TABLE propietarios ADD COLUMN IF NOT EXISTS telefono TEXT;
ALTER TABLE propietarios ADD COLUMN IF NOT EXISTS email TEXT;

ALTER TABLE propiedades ADD COLUMN IF NOT EXISTS alquiler NUMERIC DEFAULT 0;
ALTER TABLE propiedades ADD COLUMN IF NOT EXISTS propietario_id BIGINT REFERENCES propietarios(id) ON DELETE CASCADE;

ALTER TABLE inquilinos ADD COLUMN IF NOT EXISTS telefono TEXT;
ALTER TABLE inquilinos ADD COLUMN IF NOT EXISTS email TEXT;

ALTER TABLE contratos ADD COLUMN IF NOT EXISTS propiedad_id BIGINT REFERENCES propiedades(id) ON DELETE CASCADE;
ALTER TABLE contratos ADD COLUMN IF NOT EXISTS inquilino_id BIGINT REFERENCES inquilinos(id) ON DELETE CASCADE;
ALTER TABLE contratos ADD COLUMN IF NOT EXISTS alquiler NUMERIC DEFAULT 0;
ALTER TABLE contratos ADD COLUMN IF NOT EXISTS fecha_inicio DATE;
ALTER TABLE contratos ADD COLUMN IF NOT EXISTS fecha_fin DATE;
ALTER TABLE contratos ADD COLUMN IF NOT EXISTS estado TEXT DEFAULT 'Vigente';

ALTER TABLE impuestos ADD COLUMN IF NOT EXISTS propiedad_id BIGINT REFERENCES propiedades(id) ON DELETE CASCADE;
ALTER TABLE impuestos ADD COLUMN IF NOT EXISTS concepto TEXT;
ALTER TABLE impuestos ADD COLUMN IF NOT EXISTS importe NUMERIC DEFAULT 0;
ALTER TABLE impuestos ADD COLUMN IF NOT EXISTS pagador TEXT DEFAULT 'Inquilino';
ALTER TABLE impuestos ADD COLUMN IF NOT EXISTS periodo TEXT DEFAULT 'Mensual';
ALTER TABLE impuestos ADD COLUMN IF NOT EXISTS activo BOOLEAN DEFAULT true;

ALTER TABLE servicios ADD COLUMN IF NOT EXISTS propiedad_id BIGINT REFERENCES propiedades(id) ON DELETE CASCADE;
ALTER TABLE servicios ADD COLUMN IF NOT EXISTS concepto TEXT;
ALTER TABLE servicios ADD COLUMN IF NOT EXISTS importe NUMERIC DEFAULT 0;
ALTER TABLE servicios ADD COLUMN IF NOT EXISTS pagador TEXT DEFAULT 'Inquilino';
ALTER TABLE servicios ADD COLUMN IF NOT EXISTS periodo TEXT DEFAULT 'Mensual';
ALTER TABLE servicios ADD COLUMN IF NOT EXISTS activo BOOLEAN DEFAULT true;

ALTER TABLE cobranzas ADD COLUMN IF NOT EXISTS contrato_id BIGINT REFERENCES contratos(id) ON DELETE CASCADE;
ALTER TABLE cobranzas ADD COLUMN IF NOT EXISTS contrato TEXT;
ALTER TABLE cobranzas ADD COLUMN IF NOT EXISTS alquiler NUMERIC DEFAULT 0;
ALTER TABLE cobranzas ADD COLUMN IF NOT EXISTS impuestos NUMERIC DEFAULT 0;
ALTER TABLE cobranzas ADD COLUMN IF NOT EXISTS servicios NUMERIC DEFAULT 0;
ALTER TABLE cobranzas ADD COLUMN IF NOT EXISTS total NUMERIC DEFAULT 0;
ALTER TABLE cobranzas ADD COLUMN IF NOT EXISTS estado TEXT DEFAULT 'Pendiente';
ALTER TABLE cobranzas ADD COLUMN IF NOT EXISTS fecha_vencimiento DATE;
ALTER TABLE cobranzas ADD COLUMN IF NOT EXISTS fecha_pago DATE;

ALTER TABLE liquidaciones ADD COLUMN IF NOT EXISTS contrato_id BIGINT REFERENCES contratos(id) ON DELETE CASCADE;
ALTER TABLE liquidaciones ADD COLUMN IF NOT EXISTS alquiler NUMERIC DEFAULT 0;
ALTER TABLE liquidaciones ADD COLUMN IF NOT EXISTS comision NUMERIC DEFAULT 0;
ALTER TABLE liquidaciones ADD COLUMN IF NOT EXISTS gastos NUMERIC DEFAULT 0;
ALTER TABLE liquidaciones ADD COLUMN IF NOT EXISTS impuestos_transferidos NUMERIC DEFAULT 0;
ALTER TABLE liquidaciones ADD COLUMN IF NOT EXISTS neto NUMERIC DEFAULT 0;
ALTER TABLE liquidaciones ADD COLUMN IF NOT EXISTS estado TEXT DEFAULT 'Pendiente';
ALTER TABLE liquidaciones ADD COLUMN IF NOT EXISTS fecha DATE;
